=begin comment

MailSlurp API

MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 

The version of the OpenAPI document: 6.5.2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('MailSlurp::AttachmentControllerApi');

my $api = MailSlurp::AttachmentControllerApi->new();
isa_ok($api, 'MailSlurp::AttachmentControllerApi');

#
# upload_attachment test
#
{
    my $upload_options = undef; # replace NULL with a proper value
    my $result = $api->upload_attachment(upload_options => $upload_options);
}

#
# upload_attachment_bytes test
#
{
    my $string = undef; # replace NULL with a proper value
    my $filename = undef; # replace NULL with a proper value
    my $byte_array = undef; # replace NULL with a proper value
    my $result = $api->upload_attachment_bytes(string => $string, filename => $filename, byte_array => $byte_array);
}

#
# upload_multipart_form test
#
{
    my $file = undef; # replace NULL with a proper value
    my $content_type = undef; # replace NULL with a proper value
    my $filename = undef; # replace NULL with a proper value
    my $x_filename = undef; # replace NULL with a proper value
    my $result = $api->upload_multipart_form(file => $file, content_type => $content_type, filename => $filename, x_filename => $x_filename);
}


1;
