=begin comment

MailSlurp API

MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 

The version of the OpenAPI document: 6.5.2

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('MailSlurp::WaitForControllerApi');

my $api = MailSlurp::WaitForControllerApi->new();
isa_ok($api, 'MailSlurp::WaitForControllerApi');

#
# wait_for test
#
{
    my $wait_for_conditions = undef; # replace NULL with a proper value
    my $result = $api->wait_for(wait_for_conditions => $wait_for_conditions);
}

#
# wait_for_email_count test
#
{
    my $count = undef; # replace NULL with a proper value
    my $inbox_id = undef; # replace NULL with a proper value
    my $timeout = undef; # replace NULL with a proper value
    my $unread_only = undef; # replace NULL with a proper value
    my $result = $api->wait_for_email_count(count => $count, inbox_id => $inbox_id, timeout => $timeout, unread_only => $unread_only);
}

#
# wait_for_latest_email test
#
{
    my $inbox_id = undef; # replace NULL with a proper value
    my $timeout = undef; # replace NULL with a proper value
    my $unread_only = undef; # replace NULL with a proper value
    my $result = $api->wait_for_latest_email(inbox_id => $inbox_id, timeout => $timeout, unread_only => $unread_only);
}

#
# wait_for_matching_email test
#
{
    my $match_options = undef; # replace NULL with a proper value
    my $count = undef; # replace NULL with a proper value
    my $inbox_id = undef; # replace NULL with a proper value
    my $timeout = undef; # replace NULL with a proper value
    my $unread_only = undef; # replace NULL with a proper value
    my $result = $api->wait_for_matching_email(match_options => $match_options, count => $count, inbox_id => $inbox_id, timeout => $timeout, unread_only => $unread_only);
}

#
# wait_for_matching_first_email test
#
{
    my $match_options = undef; # replace NULL with a proper value
    my $inbox_id = undef; # replace NULL with a proper value
    my $timeout = undef; # replace NULL with a proper value
    my $unread_only = undef; # replace NULL with a proper value
    my $result = $api->wait_for_matching_first_email(match_options => $match_options, inbox_id => $inbox_id, timeout => $timeout, unread_only => $unread_only);
}

#
# wait_for_nth_email test
#
{
    my $inbox_id = undef; # replace NULL with a proper value
    my $index = undef; # replace NULL with a proper value
    my $timeout = undef; # replace NULL with a proper value
    my $unread_only = undef; # replace NULL with a proper value
    my $result = $api->wait_for_nth_email(inbox_id => $inbox_id, index => $index, timeout => $timeout, unread_only => $unread_only);
}


1;
